### ISSUE TITLE
InvalidOperationException when adding derived to a base-type dbset

### ISSUE THREAD

**Issue by yaseralnajjar** [BlueshiftSoftware/EntityFrameworkCore#14] opened 2017-09-18 13:50 UTC
Hi,

I added many many stuff into the demo repo:
https://github.com/0xRumple/EFMongoDemo

I started using a **base class** for the owners (Employee and Manager) which is called Owner **instead of the IOwner interface** when talking to the database cuz as you the EF core doesn't support that even in In-Memory unit tests 😞 .

In the dbsets, I used:
```
public DbSet<Owner> Owners { get; set; }
```

But this **doesn't even create a collection** in the db when I add an owner, instead it just causes an exception:
```
InvalidOperationException: The entity type 'Employee' was not found. Ensure that the entity type has been added to the model.
```

I also tried specifiying which to dbset to add to by overriding the adding behavior in the OwnerRepository but same result:
```
public override async Task<Owner> Add(Owner entity)
    {
        Context.Owners.Add(entity);
        await CommitChanges();
        
        return entity;
    }
```

**For testing**, the EFMongoDemo.Tests.DataTests.CarRepositoryShould.GetById_JoinCarAndOwner shows the same result.

*P.S:
Using this will be fine:
```
public DbSet<Employee> Owners { get; set; }
```

*P.P.S:
In mssql provider if I use the base type, it will annoyingly map all the properties in both derived types, in this case both AllowedNumberToOwn and AffliatedEmployees will be mapped into one table called "**Owners**" to satisfy the EF.

**Comment by crhairr** [comment] 2017-09-18 14:09
Are you using the `[BsonKnownTypes]` attribute to declared derived types or adding them to the model on `OnModelCreating`?

The model is built when the `DbContext` is first loaded up - this is by design of EF Core itself, not a peculiarity of EFCore-MongoDB. The Model is built off of the declared `DbSet` properties on the `DbContext`, with an opportunity to expand on that through the `OnModelCreating` method. The EF Core model _only_ knows about what is declared or manually registered on the model. That is, it cannot at runtime detect that `Employee` is derived from `Owner`, and thus should go through that set.

The underlying MongoDB C# provides a declarative way to register known derived types using [`BsonKnownTypesAttribute`](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/8399bcbc12edd509012599334a95da546b91587b/src/Blueshift.EntityFrameworkCore.MongoDB.SampleDomain/ZooDbContext.cs#L49). There are tests for [polymorphic](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/8399bcbc12edd509012599334a95da546b91587b/test/Blueshift.EntityFrameworkCore.MongoDB.Tests/MongoDbContextTests.cs#L106) [entities](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/8399bcbc12edd509012599334a95da546b91587b/test/Blueshift.EntityFrameworkCore.MongoDB.Tests/MongoDbContextTests.cs#L125).

Please review the [sample domain](https://github.com/crhairr/EntityFrameworkCore.MongoDb/tree/develop/src/Blueshift.EntityFrameworkCore.MongoDB.SampleDomain) and related tests before submitting any further issues.

**Comment by crhairr** [comment] 2017-09-18 14:14
FWIW, I'm also working on expanding the documentation. The [Getting Started](https://github.com/crhairr/EntityFrameworkCore.MongoDb/wiki/Getting-Started) wiki is admittedly a bit weak right now. I do plan on expanding on it quite a bit, with deeper linking to the documentation for both EF Core and the MongoDB C# driver to help capture and explain the underlying mechanisms.

**Comment by crhairr** [comment] 2017-09-18 14:18
I'm reopening this to help prompt me to get the documentation done.

**Comment by crhairr** [comment] 2018-12-19 20:41
Closing this. The documentation project has taken on a life of its own.

**Closed as completed by crhairr** 2018-12-19 20:41 UTC
Labels: enhancement
