### ISSUE TITLE
Package is expecting wrong version of Microsoft.EntityFrameworkCore 

### ISSUE THREAD

**Issue by Murf** [BlueshiftSoftware/EntityFrameworkCore#6] opened 2017-04-30 02:45 UTC
When I run the following command:
Install-Package Blueshift.EntityFrameworkCore.MongoDB -Version 2.0.0-preview-t0045b4d83 -Source https://www.myget.org/F/efcore-mongodb/api/v3/index.json

I get this warning in the output:
Detected package downgrade: Microsoft.EntityFrameworkCore from 2.0.0-preview1-24639 to 1.1.1 
 MyApp (>= 1.0.0) -> Blueshift.EntityFrameworkCore.MongoDB (>= 2.0.0-preview-t0045b4d83) -> Microsoft.EntityFrameworkCore (>= 2.0.0-preview1-24639) 
 MyApp (>= 1.0.0) -> Microsoft.EntityFrameworkCore (>= 1.1.1)

When I try and use the following in my app:
optionsBuilder.UseMongoDb(mongoClient);

I get the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1705	Assembly 'Blueshift.EntityFrameworkCore.MongoDB' with identity 'Blueshift.EntityFrameworkCore.MongoDB, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.EntityFrameworkCore' with identity 'Microsoft.EntityFrameworkCore, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	MyApp	C:\Users\user\documents\visual studio 2017\Projects\MyApp\MyApp\Model\MongoDbContext.cs	31	Active

**Comment by crhairr** [comment] 2017-04-30 21:59
[Duplicate of #3](3).

**Closed as completed by crhairr** 2017-04-30 21:59 UTC
Labels: duplicate
